- hosts: '{{ host }}'
  become: yes
  remote_user: root
  gather_facts: True
  vars:
    renew_certification : true
    nginx_user: '{{ nginx_user }}'
    nginx_pass: '{{ nginx_pass }}'
  pre_tasks:
    - set_fact:
        host_ip: "{{ ansible_default_ipv4.address }}"
    - debug: var=ansible_all_ipv4_addresses
    - debug: var=ansible_default_ipv4.address
  roles:
  - docker

