    - name: Check if Docker is installed
      command: docker --version
      register: docker_installed
      ignore_errors: yes

    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o /root/get-docker.sh
        bash /root/get-docker.sh
      when: docker_installed.failed

    - name: Create Nginx container
      command: docker run -d --name test -e USER='{{nginx_user}}' -e PASS='{{nginx_pass}}' nginx
      when: not docker_installed.failed