name: Test Ansible

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  remote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: interview.yml
          directory: ./
          key: ${{secrets.SSH_PRIVATE_KEY}}
          options: |
            --inventory hosts
            --extra-vars host=lab "nginx_user=$secrets.NGINX_USER nginx_pass=$secrets.NGINX_PASS"
            --verbose